config/routes.rb
Rails.application.routes.draw do

  root 'staticpages#top'

  resources :users, only: %i[new create destroy]
  resources :boards do
    collection do
      get :mypage
    end
  end
  resource :profiles
  resources :bookmarks, only: %i[create destroy]

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'users/new'

  get 'pages/terms_of_use', to: 'pages#terms_of_use'
  get 'pages/privacy_policy', to: 'pages#privacy_policy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[edit update]
  def show; end
  def edit; end

  def update
    if @user.update(user_params)
      redirect_to profiles_path, notice: '更新しました'
    else
      flash.now[:error] = '更新に失敗しました'
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/views/profiles/edit.html.erb
<div class="px-6 mt-5 sm:px-24 mb-14">
  <h2 class="text-1xl lg:text-2xl mb-2">表示名変更</h2>
    <%= form_with model: @user, url: profiles_path, method: :put do |f| %>
  <div class="mb-3">
    <%= f.text_field :name, class: 'w-full px-5 py-5 bg-white border border-white rounded-lg' %>
  </div>
  <div class="flex justify-center mx-auto">
    <%= f.submit class: "btn text-slate-700 px-4 py-2 rounded-full text-sm" %>
  </div>
  <% end %>

</div>

app/views/profiles/show.html.erb
<div class="px-6 sm:px-24 mb-14">
  <h2 class="text-1xl lg:text-2xl mb-2">プロフィール設定</h2>

    <div class="flex flex-col gap-6">

      <div class="items-center px-5 py-5 bg-white border border-white rounded-lg">
        <h3 class="text-lg pb-2"><%= '表示名' %></h3>
        <div class="flex gap-2 md:gap-5">
          <p class="pl-3 text-slate-700 text-sm"><%= @current_user.name %></p>
          <p class="ml-auto mr-2 md:mr-5 text-sm hover:font-bold"><%= link_to '編集', edit_profiles_path %></p>
        </div>
      </div>

      <div class="bg-white px-5 py-5 border border-white rounded-lg">
        <h3 class="text-lg"><%= 'メールアドレス' %></h3>
        <p class="pl-3 pt-2 text-slate-700 text-sm"><%= @current_user.email %></p>
      </div>

    </div>
    <div class="py-10">
      <%= link_to '退会する', user_path(current_user.id), data: {turbo_method: :delete, turbo_confirm: 'okを押すと退会完了となります'}, class: "border rounded-full px-3 py-2 text-stone-600 hover:border-stone-600" %>
    </div>
</div>