config/routes.rb
Rails.application.routes.draw do

  root 'staticpages#top'

  resources :users, only: %i[new create destroy]
  resources :boards do
    collection do
      get :mypage
    end
  end
  resource :profiles
  resources :bookmarks, only: %i[create destroy]

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'users/new'

  get 'pages/terms_of_use', to: 'pages#terms_of_use'
  get 'pages/privacy_policy', to: 'pages#privacy_policy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_before_login_header.html.erb
<header class="text-[#302359] body-font bg-[#fbfbfb]">
  <div class="container mx-auto flex flex-wrap py-10 px-8 lg:px-20 flex-row items-center">

    <%= link_to 'Jornalip', root_path, class: "items-center mr-4 hover:text-gray-900 display:inine-block" %>
    <%# link_to root_path, class: "flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0" do %>
      <%# ---左端にロゴ--- image_tag 'Journalip.png', class: 'w-full h-auto rounded', style: 'max-width: 300px; max-height: 200px;' %>
    <%# end %>

    <!-- Desktop Menu -->
    <div class="hidden lg:block text-xs md:flex md:ml-auto flex-nowrap items-center justify-center">
      <%= link_to 'ログイン', login_path, class: "mr-4 hover:font-bold" %>
      <%= link_to '会員登録', users_new_path, class: "mr-4 hover:font-bold" %>
      <%# link_to '検索', '#', class: "mr-4 hover:text-gray-900" %>
    </div>

    <!-- mobile Menu -->
    <div class="text-xs md:hidden justify-center flex flex-col ml-auto">
      <details class="dropdown dropdown-end">
        <summary tabindex="0" role="button" class="btn m-1">
          <i class="fa-solid fa-bars fa-xl"></i>
        </summary>
          <ul tabindex="0" class="menu dropdown-content bg-base-100 rounded-box z-[1] w-52 p-2 shadow">
            <li><%= link_to 'ログイン', login_path, class: "mr-4 hover:font-bold" %></li>
            <li><%= link_to '会員登録', users_new_path, class: "mr-4 hover:font-bold" %></li>
          </ul>
      </details>
    </div>

  </div>
</header>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message|%>
  <div class="<%= flash_background_color(message_type) %>">
  <%= message %>
  </div>
<% end%>

app/views/shared/_footer.html.erb
<footer>
  <div class="border-t border-solid border-gray-400">
    <div class="px-10 py-8 md:px-32 md:py-16 lg:flex lg:gap-16 lg:items-center">
      <div>
        <h4>Journalip</h4>
      </div>
      <div class="mt-3 lg:m-0">
      <ul class="flex flex-col gap-2 md:flex-row md:gap-6 text-xs">
        <li>
        <%= link_to 'お問い合わせ', 'https://forms.gle/QYi1z5gKfc5sa2ki9' %>
        </li>
        <li>
        <%= link_to "ご利用規約", pages_terms_of_use_path %>
        </li>
        <li>
        <%= link_to 'プライバシーポリシー', pages_privacy_policy_path %>
        </li>
      </ul>
      </div>

      <p class="mt-3 text-xs lg:m-0 lg:ml-auto">Copyright &copy;-2024 Journalip</p>

    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="text-[#302359] body-font bg-[#fbfbfb]">
  <div class="container mx-auto flex flex-wrap py-10 px-8 lg:px-20 flex-row items-center">

    <%= link_to 'Jornalip', root_path, class: "items-center mr-4 hover:text-gray-900 display:inine-block" %>

    <%# link_to root_path, class: "flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0" do %>
      <%# ---左端にロゴ--- image_tag 'Journalip.png', class: 'w-full h-auto rounded', style: 'max-width: 300px; max-height: 200px;' %>
    <%# end %>
    <!-- tablet-Desktop Menu -->
    <div class="hidden lg:block text-xs md:flex md:ml-auto flex-nowrap items-center justify-center">
      <%= link_to 'マイページ', mypage_boards_path, class: "mr-4 hover:font-bold" %>
      <%= link_to '投稿', new_board_path, data: { turbo: false }, class: "mr-4 hover:font-bold" %>
      <%= link_to '一覧', boards_path, class: "mr-4 hover:font-bold" %>
      <%= link_to 'ログアウト', logout_path, data: { turbo_method: :delete }, class: "hover:font-bold" %>
    </div>

    <!-- mobile Menu -->
    <div class="text-xs md:hidden justify-center flex flex-col ml-auto">
      <details class="dropdown dropdown-end">
        <summary tabindex="0" role="button" class="btn m-1">
          <i class="fa-solid fa-bars fa-xl"></i>
        </summary>
          <ul tabindex="0" class="dropdown-content z-[2] menu p-2 shadow bg-base-100 rounded-box w-52">
            <li><%= link_to 'マイページ', mypage_boards_path, class: "mr-4 hover:font-bold" %></li>
            <li><%= link_to '投稿', new_board_path, data: { turbo: false }, class: "mr-4 hover:font-bold" %></li>
            <li><%= link_to '一覧', boards_path, class: "mr-4 hover:font-bold" %></li>
            <li><%= link_to 'ログアウト', logout_path, data: { turbo_method: :delete }, class: "hover:font-bold" %></li>
      </details>
    </div>

  </div>
</header>