config/routes.rb
Rails.application.routes.draw do

  root 'staticpages#top'

  resources :users, only: %i[new create destroy]
  resources :boards do
    collection do
      get :mypage
    end
  end
  resource :profiles
  resources :bookmarks, only: %i[create destroy]

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'users/new'

  get 'pages/terms_of_use', to: 'pages#terms_of_use'
  get 'pages/privacy_policy', to: 'pages#privacy_policy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/board.rb
class Board < ApplicationRecord
  mount_uploader :board_image, BoardImageUploader
  belongs_to :user
  has_many :bookmarks, dependent: :destroy

  # placeフィールドから緯度と経度を取得するためにgeocoderを設定
  geocoded_by :place
  after_validation :geocode, if: :place_changed?

  validates :title, presence: true, length: { maximum: 255 }
  validates :opinion, presence: true, length: { maximum: 65_535 }
  validates :background, presence: true, length: { maximum: 65_535 }
  validates :emotion, presence: true, length: { maximum: 255 }
  validates :value, presence: true, length: { maximum: 65_535 }
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  include ApplicationHelper
  skip_before_action :require_login, only: %i[index show]
  before_action :set_board, only: %i[edit update destroy]

  def index
    @boards = Board.includes(:user)
  end

  def show
    @board = Board.find(params[:id])

    # 動的OGP
    image_path = ActionController::Base.helpers.image_url('Xcard.png')
    set_board_meta_tags(@board, image_path)
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      # 記事詳細に遷移するためリダイレクト先にIDを指定する
      redirect_to board_path(@board), notice: '記事を作成しました'
    else
      flash.now[:alert] = '記事作成に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @board.update(board_params)
      redirect_to board_path(@board), notice: '記事を更新しました'
    else
      flash.now[:alert] = '更新に失敗しました'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @board.destroy!
    redirect_to boards_path, status: :see_other, alert: '削除しました'
  end

  def mypage
    # ログインユーザの投稿を取得
    @boards = current_user.boards

    # ブックマーク一覧を取得 （一覧ページを別で作りたい場合はアクションとルーティングを設定）
    @bookmark_boards = current_user.bookmark_boards.includes(:user).order(created_at: :desc)
  end

  private

  def set_board
    @board = current_user.boards.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title, :opinion, :background, :emotion, :value, :board_image, :board_image_cache, :place)
  end
end

app/views/boards/_board.html.erb
<div class="container">
  <div class="flex justify-center items-center">
    <div class="card w-96 my-3 mx-3 bg-base-100 shadow-xl">
      <div class="card-body">
        <h2 class="card-title text-2xl"><%= link_to board.title, board_path(board) %></h2>
        <p><%= board.user.name %></p>
        <p><%= l board.created_at, format: :short %></p>
      <% if current_user && current_user.own?(board) %>
        <div class='ml-auto'>
        <%= link_to '編集', edit_board_path(board), id: "button-edit-#{board.id}" %>
        <%= link_to '削除', board_path(board), id: "button-delete-#{board.id}", data: {turbo_method: :delete, turbo_confirm: '削除しますか'} %>
        </div>
      <% else %>
        <%= render 'boards/bookmark_buttons', { board: board } %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/boards/_bookmark.html.erb
<%= link_to bookmarks_path(board_id: board.id), id: "bookmark-button-for-board-#{board.id}", data: { turbo_method: :post } do %>
  <i class="fa fa-bookmark" aria-hidden="true"></i>
<% end %>

app/views/boards/_bookmark_buttons.html.erb
<%# ログインしている場合のみブックマークの有無を表示 %>

<div class="ms-auto">
    <% if current_user %>
        <% if current_user.bookmark?(board) %>
            <%= render 'boards/unbookmark', { board: board } %>
        <% else %>
            <%= render 'boards/bookmark', { board: board } %>
        <% end %>
    <% end %>
</div>

app/views/boards/_form.html.erb
<div class="md:px-32 lg:px-52">
<%= form_with model: @board do |f| %>
  <div class="my-5">
    <p><%= f.label :place, '訪れた場所', class: "font-bold" %></p>
    <%= f.text_field :place, id: "Place", class: "w-full border-solid border rounded border-slate-400 mt-2", placeholder: '例）国、県、市' %>
  </div>
  <div class="my-5">
    <%= f.label :board_image, '添付したい画像', class: "font-bold" %>
    <%= f.file_field :board_image, class: "form-control mt-2", accept: 'image/*' %>
    <%= f.hidden_field :board_image_cache %>

    <% if board.board_image.present? %>
      <div class="mb-4">
        <%= image_tag board.board_image.url, alt: "Current Image", class: "mt-2 w-full" %>
      </div>
    <% end %>
  </div>
  <div class="my-5">
    <p><%= f.label :title, '旅で印象に残ったこと（タイトル）', class: "font-bold" %></p>
    <%= f.text_field :title, class: "w-full border-solid border rounded border-slate-400 mt-2", placeholder: '例）大阪での発見' %>
  </div>
  <div class="my-5">
    <p><%= f.label :opinion, '印象に残った具体的な内容', class: "font-bold" %></p>
    <%= f.text_area :opinion, class: "w-full h-14 border-solid border rounded border-slate-400 mt-2", placeholder: '例）大阪ではエスカレータは右に並ぶ' %>
  </div>
  <div class="my-5">
    <p><%= f.label :background, '印象に残った理由（過去の経験や知識）', class: "font-bold" %></p>
    <%= f.text_area :background, class: "w-full h-14 border-solid border rounded border-slate-400 mt-2", placeholder: '例）エスカレータで並ぶ時は世界共通で左だと思っていた' %>
  </div>
  <div class="my-5">
    <p><%= f.label :emotion, 'その経験を通して、どんな感情や気持ちが湧きましたか?', class: "font-bold" %></p>
    <%= f.text_field :emotion, class: "w-full border-solid border rounded border-slate-400 mt-2", placeholder: '例）驚き 面白い' %>
  </div>
  <div class="my-5">
    <p><%= f.label :value, 'この経験からあなたが学んだことや、重要だと思うこと', class: "font-bold" %></p>
    <%= f.text_area :value, class: "w-full h-14 border-solid border rounded border-slate-400 mt-2", placeholder: '例）新しいことを知った時に面白いと思える' %>
  </div>
  <div class="flex justify-center mt-10">
    <%= f.submit '投稿', class: "btn"%>
  </div>
<% end %>
</div>

app/views/boards/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(board_id: board.id)), id: "unbookmark-button-for-board-#{board.id}", data: { turbo_method: :delete } do %>
  <i class="fa fa-bookmark-o" aria-hidden="true"></i>
<% end %>

app/views/boards/edit.html.erb
<div class="flex justify-center items-center">
  <div class="grid-rows-4">
<h3 class="lg:text-2xl"><%= '記事編集' %></h3>
<%= render 'form', board: @board %>
  </div>
</div>

app/views/boards/index.html.erb
<div>
  <div class="px-10 mb-24">
  <h3 class="lg:text-2xl lg:px-14 my-10"><%= 'みんなの記事一覧' %></h3>
    <% if @boards.present? %>
    <div class="flex-wrap sm:px-20 sm:grid grid-cols-2 lg:grid-cols-3 grid-rows-auto gap-5">
      <%= render @boards %>
    </div>
    <% else %>
      <div class="mb-3">掲示板がありません</div>
    <% end %>
  </div>
</div>

app/views/boards/mypage.html.erb
<div class="sm:px-20 py-6 sm:py-6 lg:py-2">
  <div class="py-3 px-6">
  <h3 class="text-1xl lg:text-2xl mb-2"><%= 'プロフィール' %></h3>
    <div class="items-center px-5 py-5 flex gap-2 md:gap-5 bg-white border border-white rounded-lg">
      <div class="text-lg"><%= '表示名' %></div>
      <div class="text-slate-700"><%= @current_user.name %></div>
      <div class="ml-auto md:mr-5 hover:font-bold"><%= link_to 'みる', profiles_path %></div>
    </div>
  </div>
</div>

<div class="px-4 py-1 sm:py-8 lg:py-3">
  <h3 class="px-2 sm:pl-24 lg:text-2xl my-2"><%= '自分の記事一覧' %></h3>

    <% if @boards.present? %>
    <div class="flex-wrap sm:px-20 sm:grid grid-cols-2 lg:grid-cols-3 grid-rows-auto gap-5">
      <%= render @boards %>
    </div>
    <% else %>
      <div class="m-auto pt-10 pb-20 text-center">掲示板がありません</div>
    <% end %>
    <div class="flex justify-center">
    <%= link_to '投稿する', new_board_path, class: 'btn'%>
    </div>


  <h3 class="px-2 sm:pl-24 lg:text-2xl my-2"><%= 'ブックマーク一覧' %></h3>

    <% if @bookmark_boards.present? %>
      <%= render @bookmark_boards %>
      <% else %>
      <div class="m-auto pt-10 pb-20 text-center">ブックマークがありません</div>
    <% end %>

</div>

app/views/boards/new.html.erb
<div>
  <div class="px-10 mb-24">
    <h3 class="lg:text-2xl md:px-32 lg:px-52 mt-10"><%= '記事投稿' %></h3>
    <%= render 'form', board: @board %>
  </div>
</div>

<%# GoogleMapAPI読み込み %>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_MAP_API_KEY"] %>&libraries=places&callback=initialize" defer></script>

app/views/boards/show.html.erb
<div class="container">
  <div class="mb-10 px-5 mb4 md:px-32 lg:px-52">

<% if @board.board_image.present? %>
    <%= image_tag @board.board_image_url, class: "object-contain w-full" %>
<% end %>

  <h2 class="my-6 text-xl font-bold"><%= "#{@board.title}" %></h2>

<ul>
  <li>
    <div class="inline-flex">
      <%= '訪れた場所:' %>
      <%= @board.place %>
    </div>
  </li>
  <li>
    <div class="inline-flex">
      <%= '投稿者:' %>
      <%= @board.user.name %>
    </div>
  </li>
  <li>
    <div class="inline-flex mb-6">
      <%= '投稿日時:' %>
      <%= l @board.created_at, format: :long %>
    </div> 
  </li>
</ul>

<p class="mb-1 font-bold"><%= '印象に残った具体的な内容' %></p>
<div class="w-full mb-6 py-1 px-1 border-solid border rounded border-slate-400">
<%= simple_format(@board.opinion) %>
</div>

<p class="mb-1 font-bold"><%= '印象に残った理由（過去の経験や知識）' %></p>
<div class="w-full mb-6 py-1 px-1 border-solid border rounded border-slate-400">
<%= simple_format(@board.background) %>
</div>

<p class="mb-1 font-bold"><%= 'その経験を通して、どんな感情や気持ちが湧きましたか?' %></p>
<div class="w-full mb-6 py-1 px-1 border-solid border rounded border-slate-400">
<%= simple_format(@board.emotion) %>
</div>

<p class="mb-1 font-bold"><%= 'この経験からあなたが学んだことや、重要だと思うこと' %></p>
<div class="w-full h-14 mb-6 py-1 px-1 border-solid border rounded border-slate-400">
<%= simple_format(@board.value) %>
</div>

<%#　訪れた場所に入力がある場合に地図を表示する　%>
<% if @board.place.present? %>
  <div id="map" class="h-60 w-full"></div>

<script>
  // 地図を表示する関数
  function displayMap() {
    let location = {lat: <%= @board.latitude %>, lng: <%= @board.longitude %>};
    console.log(location);
    const mapOptions = {
    center: location,
    zoom: 13,
    streetViewControl: false, // ストリートビューのボタン非表示
    fullscreenControl: false, // フルスクリーンボタン非表示
    mapTypeControl: false, // 地図、航空写真のボタン非表示
  };

  const mapDiv = document.getElementById('map');
  const map = new google.maps.Map(mapDiv, mapOptions);

  const markerOptions = {
    position: location,
    map: map
  };
  const marker = new google.maps.Marker(markerOptions)
  }

  // Google Maps APIロード後に呼び出されるコールバック関数
  function initMap() {
    console.log("Google Maps APIが読み込まれました。");
    displayMap();
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
<% end %>

<% if current_user && current_user.own?(@board) %>
  <div class="flex justify-center mt-10">
    <% share_text = "旅行の思い出を投稿しました！\n\n【#{@board.title}】\n#Journalip\n" %>
    <% share_url = board_url(@board) %>
      <%= link_to "https://twitter.com/intent/tweet?text=#{ERB::Util.url_encode(share_text)}&url=#{ERB::Util.url_encode(share_url)}", target: "_blank", rel: "noopener" do %>
      <p class="btn"><i class="fa-brands fa-x-twitter font-bold fa-lg"></i>で共有する</p>
      <% end %>
<% end %>



</div>
<div class="flex justify-center mt-2">
  <%= link_to '一覧に戻る', boards_path, class: 'btn mt-3'%>
  </div>
</div>
</div>