config/routes.rb
Rails.application.routes.draw do

  root 'staticpages#top'

  resources :users, only: %i[new create destroy]
  resources :boards do
    collection do
      get :mypage
    end
  end
  resource :profiles
  resources :bookmarks, only: %i[create destroy]

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'users/new'

  get 'pages/terms_of_use', to: 'pages#terms_of_use'
  get 'pages/privacy_policy', to: 'pages#privacy_policy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to root_path, notice: 'ログインしました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, alert: 'ログアウトしました'
  end
end

app/views/user_sessions/new.html.erb
<div class="py-6 px-6 sm:py-8 lg:py-12">
  <div class="mx-auto py-9">
    <h2 class="mb-4 text-center text-2xl font-bold text-gray-800 md:mb-8 lg:text-3xl">ログイン</h2>
    <%= form_with url: login_path, class: "mx-auto max-w-lg rounded-lg border" do |f| %>
    <div class="flex flex-col gap-4 p-4 md:p-8">
    <div>
      <%= f.label :email, class: "inline-block text-sm" %>
      <%= f.email_field :email, class: "w-full rounded border px-3 py-2" %>
    </div>
    <div>
      <%= f.label :password, class: "inline-block text-sm" %>
      <%= f.password_field :password, class: "w-full rounded border px-3 py-2" %>
    </div>
    <%= f.submit "ログイン", class: "btn" %>
    <div class="border-b my-2"></div>

    <div>
      <%= link_to auth_at_provider_path(provider: :google), class: "btn w-full text-gray-900" do %>
      <svg class="h-5 w-5 shrink-0" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M23.7449 12.27C23.7449 11.48 23.6749 10.73 23.5549 10H12.2549V14.51H18.7249C18.4349 15.99 17.5849 17.24 16.3249 18.09V21.09H20.1849C22.4449 19 23.7449 15.92 23.7449 12.27Z" fill="#4285F4" />
        <path d="M12.2549 24C15.4949 24 18.2049 22.92 20.1849 21.09L16.3249 18.09C15.2449 18.81 13.8749 19.25 12.2549 19.25C9.12492 19.25 6.47492 17.14 5.52492 14.29H1.54492V17.38C3.51492 21.3 7.56492 24 12.2549 24Z" fill="#34A853" />
        <path d="M5.52488 14.29C5.27488 13.57 5.14488 12.8 5.14488 12C5.14488 11.2 5.28488 10.43 5.52488 9.71V6.62H1.54488C0.724882 8.24 0.254883 10.06 0.254883 12C0.254883 13.94 0.724882 15.76 1.54488 17.38L5.52488 14.29Z" fill="#FBBC05" />
        <path d="M12.2549 4.75C14.0249 4.75 15.6049 5.36 16.8549 6.55L20.2749 3.13C18.2049 1.19 15.4949 0 12.2549 0C7.56492 0 3.51492 2.7 1.54492 6.62L5.52492 9.71C6.47492 6.86 9.12492 4.75 12.2549 4.75Z" fill="#EA4335" />
      </svg>
      Login with Google
      <% end %>
    </div>

  <div class="border-b my-2"></div>

<%= link_to 'はじめての方はこちら', new_user_path, class: "text-center" %>
<%# link_to 'パスワードをお忘れの方はこちら', '#' %>
<% end %>
</div>
</div>
</div>